name: app_noticias
description: "App de noticias conectada a WordPress."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ðŸ”¥ Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^17.2.1

  # ðŸ“¸ Imagen + Recorte
  image_picker: ^1.0.7
  image_cropper: ^8.0.2

  # ðŸŽ iOS Icons
  cupertino_icons: ^1.0.8

  # ðŸŒ Networking
  http: ^1.6.0
  dio: ^5.6.0

  # ðŸ”„ BLoC
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # ðŸ§± JSON / Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # ðŸ“° HTML WordPress
  flutter_html: ^3.0.0

  # ðŸ’¾ Persistencia
  shared_preferences: ^2.5.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # ðŸŽ¨ UI
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.3
  shimmer: ^3.0.0
  intl: ^0.20.2
  url_launcher: ^6.3.2

  # ðŸ”Š Audio
  just_audio: ^0.10.5

  # ðŸ–¼ SVG
  flutter_svg: ^2.1.1

  # âœ¨ Animaciones
  animations: ^2.0.11
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  freezed: ^3.2.3
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/
    - assets/images/
