name: app_noticias
description: "App de noticias conectada a WordPress."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP
  dio: ^5.6.0

  # Estado
  provider: ^6.1.5+1

  # Modelos + JSON
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Mostrar HTML de WordPress
  flutter_html: ^3.0.0

  # Persistencia
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  http: ^1.6.0
  google_fonts: ^6.3.3
  shimmer: ^3.0.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  just_audio: ^0.10.5
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Generadores de Freezed y JSON
  build_runner: ^2.4.8
  freezed: ^2.5.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
